//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class molecule : serialisable
	{
		public string name;
		public int ID;
		public float rarity;
		public bool complex;
		public int size;
		public int componantID;
		public molecule componant;

		public molecule ()
		{
		}
	}
}

