//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class RandomPolynom
	{
		private float _A;
		private float _B;
		private float _C;

		public RandomPolynom()
		{
			newPolynom ();
		}

		public void newPolynom(float infBoundA, float supBoundA, float infBoundB, float supBoundB, float infBoundC, float supBoundC)
		{
			_A = UnityEngine.Random.Range (infBoundA, supBoundA);
			_B = UnityEngine.Random.Range (infBoundB, supBoundB);
			_C = UnityEngine.Random.Range (infBoundC, supBoundC);
		}

		public void newPolynom()
		{
			float infBoundA = NextFloat();
			float supBoundA = NextFloat();
			float infBoundB = NextFloat();
			float supBoundB = NextFloat();
			float infBoundC = NextFloat();
			float supBoundC = NextFloat();
			swap (ref infBoundA, ref supBoundA);
			swap (ref infBoundB, ref supBoundB);
			swap (ref infBoundC, ref supBoundC);
			newPolynom (infBoundA, supBoundA, infBoundB, supBoundB, infBoundC, supBoundC);
		}

		public float f(float x)
		{
			float r = (_A * x * x + _B * x + _C);
			if (0 > r) 
			{
				return 0f;
			}
			return r;
		}

		public float NextFloat(System.Random random)
		{
			double mantissa = (random.NextDouble() * 2.0) - 1.0;
			double exponent = Math.Pow(2.0, random.Next(-126, 128));
			return (float)(mantissa * exponent);
		}

		public float NextFloat()
		{
			return NextFloat(new System.Random());
		}

		public void swap(ref float a, ref float b)
		{
			if (a > b) 
			{
				float t = a;
				a = b;
				b = t;
			}
		}

		public float A
		{
			get
			{
				return _A;
			}
			set
			{
				_A = value;
			}
		}

		public float B
		{
			get
			{
				return _B;
			}
			set
			{
				_B = value;
			}
		}

		public float C
		{
			get
			{
				return _C;
			}
			set
			{
				_C = value;
			}
		}
	}
}

