//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace AssemblyCSharp
{
	public class skill : serialisable
	{
		public int ID;
		public int[] neighborsID;
		public string name;
		public string description;
		
		public actionData workCosts;
		public actionData workProducts;
		public actionData devCosts;
		public actionData devProducts;
		
		public bool innate;
		public string type;
		public List<int> requiredID;
		
		[XmlIgnore]
		private List<skill> _required;
		[XmlIgnore]
		private skill[] _neighbors;
		[XmlIgnore]
		public GameObject hex;
		[XmlIgnore]
		public bool treated = false;
		[XmlIgnore]
		public bool accessible = false;
		[XmlIgnore]
		public bool unlockable = false;
		[XmlIgnore]
		public bool unlocked = false;
		
		public skill(skill[] neighbors, string name, string description, actionData workCosts, actionData workProducts, actionData devCosts, actionData devProducts, bool innate, string type, List<skill> required)
		{
			this.ID = -1;
			_neighbors = neighbors;
			this.name = name;
			this.description = description;
			this.workCosts = workCosts;
			this.workProducts = workProducts;
			this.devCosts = devCosts;
			this.devProducts = devProducts;
			this.innate = innate;
			this.type = type;
			_required = required;
			this.requiredID = new List<int>();
			this.SerialisableType = serialisableTypes.skill;
			this.neighborsID = new int[6] { -1, -1, -1, -1, -1, -1 };
			this.unlocked = innate;
		}
		
		public skill()
		{
			this.ID = -1;
			_neighbors = new skill[6] ;
			this.name = "unvalid name";
			this.description = "no description";
			this.workCosts = new actionData();
			this.workProducts = new actionData();
			this.devCosts = new actionData();
			this.devProducts = new actionData();
			this.innate = false;
			_required = new List<skill>();
			this.requiredID = new List<int>();
			this.type = "unvalid";
			this.SerialisableType = serialisableTypes.skill;
			this.neighborsID = new int[6] { -1, -1, -1, -1, -1, -1 };
			this.unlocked = innate;
		}

		
		public override string ToString()
		{
			return name;
		}

		public skill[] neighbors
		{
			get
			{
				return _neighbors;
			}
		}

		public List<skill> required
		{
			get
			{
				return _required;
			}
		}
	}
}

