//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class moleculePack : serialisable
	{
		public molecule moleculeType;
		public int count;



		public moleculePack(int count, molecule moleculeType)
		{
			this.count = count;
			this.moleculeType = moleculeType;
			this.SerialisableType = serialisableTypes.moleculePack;
		}
		
		public moleculePack() : this(1, new molecule())
		{
			
		}

		public static moleculePack operator + (moleculePack mp1, moleculePack mp2)
		{
			if (mp1.moleculeType.ID == mp2.moleculeType.ID) 
			{
				return new moleculePack (mp1.count + mp2.count, mp1.moleculeType);
			} 
			else 
			{
				throw new ArgumentException("These two moleculePacks are of the same type: " + mp1.moleculeType.name + ", " + mp2.moleculeType.name);
			}
		}

		public delegate int operation(ref int source, ref int destination);
		
		public static void moleculeListFusion(List<moleculePack> src, List<moleculePack> dst, operation action)
		{
			foreach (moleculePack mpS in src) 
			{
				int i = dst.FindIndex(mpD => mpD.moleculeType.ID == mpS.moleculeType.ID);
				if (i == -1)
				{
					dst.Add(mpS);
				}
				else
				{
					dst[i].count = action(ref mpS.count, ref dst[i].count);
				}
			}
		}
	}
}

