//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class moleculePack : serialisable
	{
		public molecule moleculeType;
		public int count;

		public moleculePack(int count, molecule moleculeType)
		{
			this.count = count;
			this.moleculeType = moleculeType;
			this.SerialisableType = serialisableTypes.moleculePack;
		}
		
		public moleculePack() : this(1, new molecule())
		{
			
		}
	}
}

