//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class perkData
	{
		public int[] neigborsID = new int[6];
		public string description = "";
		public int ID = -1;
		public string name = "";
		public bool drawn;
		public GameObject hex;

		public perkData (string name, int[] neighborsID, string description, int ID)
		{
			this.neigborsID = neighborsID;
			this.description = description;
			this.ID = ID;
			this.drawn = false;
		}

		public perkData ()
		{
			this.drawn = false;
		}
	}
}

