//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;

namespace AssemblyCSharp
{
	[XmlInclude(typeof(skill))]
	[XmlInclude(typeof(molecule))]
	public class serialisable
	{
		public serialisableTypes SerialisableType;
		
		public serialisable()
		{
			SerialisableType = serialisableTypes.unvalid;
		}
	}
}

